<?php

return [
    'title'=>'Reports','report'=>'Report','website'=>'Website','keyword'=>'Keyword','start_date'=>'Start date','end_date'=>'End date','device'=>'Device','country'=>'Country','search_type'=>'Search type','query'=>'Query','page_url'=>'Page URL','apply'=>'Apply filters','export_csv'=>'Export UTF-8 CSV','access_denied'=>'Access denied','unavailable'=>'Reports are unavailable.','pagination'=>'Page :page of :pages — :total rows',
    'type_website'=>'Website report','type_keyword'=>'Keyword report','type_ranking'=>'Ranking report','type_search_console'=>'Search Console report','type_improved'=>'Improvement report','type_dropped'=>'Dropped keywords','type_top10'=>'Top 10 keywords','type_top3'=>'Top 3 keywords','type_number1'=>'#1 keywords',
    'source_rank_tracker'=>'Source: Rank Tracker observed positions','source_search_console'=>'Source: Google Search Console aggregated metrics','state_empty'=>'No ranking data matches these filters.','state_no_search_console_data'=>'No Search Console data matches these filters.','state_module_disabled'=>'Search Console is disabled; Rank Tracker reports remain available.',
    'option_all'=>'All','option_desktop'=>'Desktop','option_mobile'=>'Mobile','option_tablet'=>'Tablet','option_web'=>'Web','option_image'=>'Image','option_video'=>'Video','option_news'=>'News','option_discover'=>'Discover','option_googleNews'=>'Google News',
    'column_website_id'=>'Website ID','column_site_name'=>'Website','column_canonical_url'=>'Canonical URL','column_status'=>'Status','column_keywords'=>'Keywords','column_rank_observations'=>'Rank observations','column_keyword_id'=>'Keyword ID','column_keyword_text'=>'Keyword','column_search_engine'=>'Search engine','column_country_code'=>'Country','column_language_code'=>'Language','column_device'=>'Device','column_active'=>'Active','column_current_position'=>'Rank Tracker current position','column_previous_position'=>'Rank Tracker previous position','column_change'=>'Rank Tracker change','column_result_type'=>'Result','column_rank_tracker_position'=>'Rank Tracker observed position','column_ranking_url'=>'Ranking URL','column_observed_at'=>'Observed at','column_query_text'=>'Search Console query','column_page_url'=>'Search Console page','column_country'=>'Country','column_search_type'=>'Search type','column_clicks'=>'Clicks','column_impressions'=>'Impressions','column_ctr'=>'CTR','column_search_console_average_position'=>'Search Console average position',
];
