<?php
return [
 'validation.action'=>'The action could not be completed.','validation.unauthorized'=>'You are not authorized to perform this action.','validation.email'=>'Enter a valid email address.','validation.admin_email'=>'Enter a valid administrator email address.','validation.name'=>'Name is required and must be 100 characters or fewer.','validation.admin_name'=>'Administrator name is required and must be 100 characters or fewer.','validation.password'=>'Password must be between 12 and 1024 characters.','validation.admin_password'=>'Administrator password must be between 12 and 1024 characters.','validation.app_name'=>'Application name is required and must be 120 characters or fewer.',
 'validation.website_missing'=>'Website not found.','validation.keyword_missing'=>'Keyword not found.','validation.user_missing'=>'User not found.','validation.role_missing'=>'Role not found.','validation.rank_missing'=>'Rank check not found.','validation.connection_missing'=>'Search Console connection not found.','validation.property_missing'=>'Search Console property not found.','validation.sync_missing'=>'Search Console sync not found.','validation.comparison_missing'=>'Comparison not found.',
 'validation.website_input'=>'Enter a valid website URL and a description of 5000 characters or fewer.','validation.website_name'=>'Site name is required and must be 150 characters or fewer.','validation.website_url'=>'Website URL must identify an origin and cannot contain a path.','validation.website_origin'=>'URL must be an HTTP or HTTPS origin without credentials, port, query, or fragment.','validation.domain'=>'Enter a valid ASCII domain. Convert international domains to Punycode first.','validation.website_duplicate'=>'This domain is already registered in your account.','validation.website_archived'=>'Website is already archived.','validation.website_archived_edit'=>'Archived websites cannot be edited.','validation.website_archived_settings'=>'Archived website settings cannot be changed.',
 'validation.keyword'=>'Keyword is required, must be 255 characters or fewer, and cannot contain control characters.','validation.keyword_duplicate'=>'This keyword tracking configuration already exists for the website.','validation.keyword_archived'=>'Archived websites cannot modify keywords.','validation.keyword_active'=>'Only active keywords can be checked.','validation.target_url'=>'Target URL must be a valid HTTP or HTTPS URL.','validation.target_url_safe'=>'Target URL must be HTTP or HTTPS and cannot contain credentials or a fragment.','validation.engine'=>'Select a supported search engine.','validation.country'=>'Select a supported ISO 3166-1 alpha-2 country.','validation.language'=>'Language must be a valid BCP 47-style language tag.','validation.device'=>'Select a supported device.','validation.timezone_status'=>'Select a valid timezone and status.',
 'validation.rate_rank'=>'Rank check rate limit reached. Wait before trying again.','validation.rank_disabled'=>'Manual rank checks are temporarily disabled.','validation.rank_archived'=>'Archived websites cannot run rank checks.','validation.rank_adapter'=>'No approved Rank Tracking adapter is configured.','validation.rank_url'=>'Invalid ranking URL.','validation.rank_result'=>'Invalid rank result classification.',
 'validation.sc_disabled'=>'Search Console is disabled.','validation.sc_not_connected'=>'Search Console is not connected.','validation.sc_dates'=>'Search Console dates must be within the available history and configured range limit.','validation.sc_range'=>'Select a valid Search Console date range.','validation.sc_dashboard_range'=>'Select a valid Search Console dashboard date range.','validation.sc_filters'=>'Select valid Search Console dashboard filters.','validation.sc_type'=>'Select a supported Search Console search type.','validation.sc_rate'=>'Search Console sync rate limit reached. Try again later.','validation.sc_sync_disabled'=>'Search Console synchronization is temporarily disabled.','validation.query'=>'Invalid query filter.','validation.page'=>'Invalid page filter.',
 'validation.identifier'=>'Invalid identifier.','validation.pagination'=>'Invalid pagination.','validation.date_range'=>'Invalid date range.','validation.report_range'=>'Invalid report date range.','validation.report_filters'=>'Invalid report filters.','validation.report_type'=>'Unknown report type.','validation.report_disabled'=>'Reports module is disabled.','validation.csv'=>'CSV export unavailable.',
 'validation.module_state'=>'Invalid module state.','validation.module_missing'=>'Module is not installed.','validation.module_locked'=>'Foundational modules cannot be disabled.','validation.setting_scope'=>'Invalid setting scope.','validation.setting_text'=>'Invalid setting text.','validation.setting_timezone'=>'Invalid timezone.','validation.setting_secure'=>'Secure settings must be configured through deployment secrets.','validation.setting_unknown'=>'Unknown setting.','validation.setting_boolean'=>'Setting must be boolean.','validation.setting_allowed'=>'Setting value is not allowed.','validation.feature_flag'=>'Not a feature flag.',
 'validation.self_disable'=>'You cannot disable your own account.','validation.self_delete'=>'You cannot delete your own account.','validation.last_admin_disable'=>'The last active administrator cannot be disabled.','validation.last_admin_delete'=>'The last active administrator cannot be deleted.','validation.admin_role'=>'The administrator role must retain roles.manage.','validation.roles_missing'=>'One or more roles do not exist.','validation.permissions_missing'=>'One or more permissions do not exist.','validation.assignment'=>'Invalid assignment selection.',
];
