<?php

declare(strict_types=1);

namespace App\Modules\Settings\Presentation;

use App\Core\Http\Request;
use App\Core\Http\Response;
use App\Core\Rbac\AuthorizationException;
use App\Core\Security\Csrf;
use App\Core\Security\Html;
use App\Modules\Settings\Infrastructure\SettingsFactory;
use InvalidArgumentException;
use Throwable;

final class SettingsController
{
    public function __construct(private readonly SettingsFactory $factory) {}
    public function user(): Response { $t=$this->factory->translator(); try { [$settings,,$auth]=$this->factory->services(); $actor=$this->actor($auth); return $this->page($t->get('user_settings'),$this->form('/settings','user',(string)$actor,$settings->all($actor,'user',(string)$actor))); } catch(Throwable){ return $this->page($t->get('user_settings'),'<p class="error">'.$t->get('unavailable').'</p>',503); } }
    public function saveUser(Request $request): Response { try { [$settings,,$auth]=$this->factory->services(); $actor=$this->actor($auth); $settings->set($actor,(string)($request->body['key']??''),$request->body['value']??null,(string)$actor); return Response::redirect('/settings'); } catch(AuthorizationException $e){ return Response::json(['error'=>$e->getMessage()],403); } catch(Throwable $e){ return Response::json(['error'=>$e instanceof InvalidArgumentException?$e->getMessage():'Setting could not be saved.'],422); } }
    public function admin(Request $request): Response { $t=$this->factory->translator(); try { [$settings,$modules,$auth]=$this->factory->services(); $actor=$this->actor($auth); $scope=is_string($request->query['scope']??null)?$request->query['scope']:'system'; $scopeId=$scope==='module'?(is_string($request->query['module']??null)?$request->query['module']:'reports'):'global'; $content='<h2>'.$t->get('modules').'</h2><div class="table-scroll"><table><thead><tr><th>'.$t->get('module').'</th><th>'.$t->get('version').'</th><th>'.$t->get('status').'</th><th>'.$t->get('action').'</th></tr></thead><tbody>'; foreach($modules->all($actor) as $module){ $button=$module['mutable']?'<form method="post" action="/admin/modules">'.$this->csrf().'<input type="hidden" name="module" value="'.Html::escape($module['key']).'"><input type="hidden" name="enabled" value="'.($module['enabled']?'0':'1').'"><button>'.Html::escape($t->get($module['enabled']?'disable':'enable')).'</button></form>':'<span>'.$t->get('locked').'</span>'; $content.='<tr><td>'.Html::escape($module['name']).'</td><td>'.Html::escape((string)($module['version']??'—')).'</td><td>'.Html::escape($t->get($module['status'])).'</td><td>'.$button.'</td></tr>'; } $content.='</tbody></table></div><p><a href="/admin/settings">'.$t->get('system_settings').'</a> · <a href="/admin/settings?scope=module&module=reports">'.$t->get('reports').'</a> · <a href="/admin/settings?scope=module&module=search_console">'.$t->get('search_console').'</a></p><h2>'.$t->get($scope==='module'?'module_settings':'system_settings').'</h2>'.$this->form('/admin/settings',$scope,$scopeId,$settings->all($actor,$scope,$scopeId)); return $this->page($t->get('title'),$content); } catch(AuthorizationException){ return $this->page($t->get('access_denied'),'<p class="error">'.$t->get('access_denied').'</p>',403); } catch(Throwable){ return $this->page($t->get('title'),'<p class="error">'.$t->get('unavailable').'</p>',503); } }
    public function saveAdmin(Request $request): Response { try { [$settings,,$auth]=$this->factory->services(); $actor=$this->actor($auth); $scope=(string)($request->body['scope']??'system'); $id=$scope==='system'?'global':(string)($request->body['scope_id']??''); $settings->set($actor,(string)($request->body['key']??''),$request->body['value']??null,$id); return Response::redirect('/admin/settings?scope='.rawurlencode($scope).($scope==='module'?'&module='.rawurlencode($id):'')); } catch(AuthorizationException $e){ return Response::json(['error'=>$e->getMessage()],403); } catch(Throwable $e){ return Response::json(['error'=>$e instanceof InvalidArgumentException?$e->getMessage():'Setting could not be saved.'],422); } }
    public function module(Request $request): Response { try { [,$modules,$auth]=$this->factory->services(); $enabled=filter_var($request->body['enabled']??null,FILTER_VALIDATE_BOOL,FILTER_NULL_ON_FAILURE); if($enabled===null)throw new InvalidArgumentException('Invalid module state.'); $modules->setEnabled($this->actor($auth),(string)($request->body['module']??''),$enabled); return Response::redirect('/admin/settings'); } catch(AuthorizationException $e){ return Response::json(['error'=>$e->getMessage()],403); } catch(Throwable $e){ return Response::json(['error'=>$e instanceof InvalidArgumentException?$e->getMessage():'Module state could not be changed.'],422); } }
    private function form(string $action,string $scope,string $scopeId,array $rows): string { $t=$this->factory->translator(); $html=''; foreach($rows as $key=>$row){ $value=$row['value']; if($row['type']==='boolean')$input='<select name="value"><option value="1"'.($value?' selected':'').'>'.$t->get('enabled').'</option><option value="0"'.(!$value?' selected':'').'>'.$t->get('disabled').'</option></select>'; elseif($row['type']==='enum'){$input='<select name="value">';foreach($row['options'] as $option)$input.='<option value="'.Html::escape((string)$option).'"'.($value===$option?' selected':'').'>'.Html::escape((string)$option).'</option>';$input.='</select>';}else $input='<input name="value" value="'.Html::escape((string)$value).'">'; $html.='<form class="setting-row" method="post" action="'.$action.'">'.$this->csrf().'<input type="hidden" name="scope" value="'.$scope.'"><input type="hidden" name="scope_id" value="'.Html::escape($scopeId).'"><input type="hidden" name="key" value="'.Html::escape($key).'"><label>'.Html::escape($t->get('setting_'.$key)).$input.'</label><button>'.$t->get('save').'</button></form>'; } return $html; }
    private function csrf():string{return '<input type="hidden" name="_token" value="'.Html::escape(Csrf::token()).'">';} private function actor(object $auth):int{$user=$auth->user();if($user===null)throw new AuthorizationException('Authentication required.');return(int)$user['id'];} private function page(string $title,string $content,int $status=200):Response{$t=$this->factory->translator();return Response::html('<!doctype html><html lang="'.Html::escape($t->locale()).'" dir="'.($this->factory->isRtl()?'rtl':'ltr').'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.Html::escape($title).' — SEO Tracker</title><link rel="stylesheet" href="/assets/installer.css"></head><body><main class="card wide"><h1>'.Html::escape($title).'</h1>'.$content.'</main></body></html>',$status);}
}
