<?php

return [
    'title'=>'گزارش‌ها','report'=>'گزارش','website'=>'وب‌سایت','keyword'=>'کلمه','start_date'=>'تاریخ آغاز','end_date'=>'تاریخ پایان','device'=>'دستگاه','country'=>'کشور','search_type'=>'نوع جستجو','query'=>'عبارت','page_url'=>'نشانی صفحه','apply'=>'اعمال فیلتر','export_csv'=>'خروجی CSV با UTF-8','access_denied'=>'دسترسی رد شد','unavailable'=>'گزارش‌ها در دسترس نیستند.','pagination'=>'صفحه :page از :pages — :total ردیف',
    'type_website'=>'گزارش وب‌سایت','type_keyword'=>'گزارش کلمه','type_ranking'=>'گزارش رتبه','type_search_console'=>'گزارش سرچ کنسول','type_improved'=>'گزارش بهبود','type_dropped'=>'کلمات افت‌کرده','type_top10'=>'کلمات ۱۰ رتبه برتر','type_top3'=>'کلمات ۳ رتبه برتر','type_number1'=>'کلمات رتبه ۱',
    'source_rank_tracker'=>'منبع: جایگاه‌های مشاهده‌شده ردیاب رتبه','source_search_console'=>'منبع: معیارهای تجمیعی گوگل سرچ کنسول','state_empty'=>'داده رتبه‌ای با این فیلترها وجود ندارد.','state_no_search_console_data'=>'داده سرچ کنسول با این فیلترها وجود ندارد.','state_module_disabled'=>'سرچ کنسول غیرفعال است؛ گزارش‌های ردیاب رتبه در دسترس می‌مانند.',
    'option_all'=>'همه','option_desktop'=>'دسکتاپ','option_mobile'=>'موبایل','option_tablet'=>'تبلت','option_web'=>'وب','option_image'=>'تصویر','option_video'=>'ویدیو','option_news'=>'اخبار','option_discover'=>'دیسکاور','option_googleNews'=>'گوگل نیوز',
    'column_website_id'=>'شناسه وب‌سایت','column_site_name'=>'وب‌سایت','column_canonical_url'=>'نشانی اصلی','column_status'=>'وضعیت','column_keywords'=>'کلمات','column_rank_observations'=>'مشاهدات رتبه','column_keyword_id'=>'شناسه کلمه','column_keyword_text'=>'کلمه','column_search_engine'=>'موتور جستجو','column_country_code'=>'کشور','column_language_code'=>'زبان','column_device'=>'دستگاه','column_active'=>'فعال','column_current_position'=>'جایگاه فعلی ردیاب رتبه','column_previous_position'=>'جایگاه قبلی ردیاب رتبه','column_change'=>'تغییر ردیاب رتبه','column_result_type'=>'نتیجه','column_rank_tracker_position'=>'جایگاه مشاهده‌شده ردیاب رتبه','column_ranking_url'=>'نشانی رتبه‌گرفته','column_observed_at'=>'زمان مشاهده','column_query_text'=>'عبارت سرچ کنسول','column_page_url'=>'صفحه سرچ کنسول','column_country'=>'کشور','column_search_type'=>'نوع جستجو','column_clicks'=>'کلیک','column_impressions'=>'نمایش','column_ctr'=>'نرخ کلیک','column_search_console_average_position'=>'میانگین جایگاه سرچ کنسول',
];
