<?php

declare(strict_types=1);

return [
 'website'=>['label'=>'وب‌سایت','term'=>'Website'],'websites'=>['label'=>'وب‌سایت‌ها','term'=>'Websites'],'domain'=>['label'=>'دامنه','term'=>'Domain'],'keyword'=>['label'=>'کلیدواژه','term'=>'Keyword'],'keywords'=>['label'=>'کلیدواژه‌ها','term'=>'Keywords'],'target_url'=>['label'=>'نشانی هدف','term'=>'Target URL'],'search_engine'=>['label'=>'موتور جستجو','term'=>'Search Engine'],'device'=>['label'=>'دستگاه','term'=>'Device'],'desktop'=>['label'=>'رایانه رومیزی','term'=>'Desktop'],'mobile'=>['label'=>'موبایل','term'=>'Mobile'],
 'rank_tracking'=>['label'=>'ردیابی رتبه','term'=>'Rank Tracking'],'rank_check'=>['label'=>'بررسی رتبه','term'=>'Rank Check'],'rank_history'=>['label'=>'تاریخچه رتبه','term'=>'Rank History'],'rank_tracker_position'=>['label'=>'رتبه ثبت‌شده توسط ردیاب','term'=>'Rank Tracker Position','description'=>'Exact position observed by a Rank Tracking execution.'],'current_rank'=>['label'=>'رتبه فعلی','term'=>'Current Rank'],'previous_rank'=>['label'=>'رتبه قبلی','term'=>'Previous Rank'],'best_rank'=>['label'=>'بهترین رتبه','term'=>'Best Rank'],'worst_rank'=>['label'=>'بدترین رتبه','term'=>'Worst Rank'],'ranking_url'=>['label'=>'نشانی رتبه‌گرفته','term'=>'Ranking URL'],'position_change'=>['label'=>'تغییر رتبه','term'=>'Position Change'],
 'search_console'=>['label'=>'سرچ کنسول گوگل','term'=>'Google Search Console'],'property'=>['label'=>'ویژگی سرچ کنسول','term'=>'Search Console Property'],'query'=>['label'=>'عبارت جستجو','term'=>'Query'],'page'=>['label'=>'صفحه سرچ کنسول','term'=>'Page'],'clicks'=>['label'=>'کلیک‌ها','term'=>'Clicks'],'impressions'=>['label'=>'نمایش‌ها','term'=>'Impressions'],'ctr'=>['label'=>'نرخ کلیک','term'=>'CTR — Click-Through Rate'],'average_position'=>['label'=>'میانگین جایگاه سرچ کنسول','term'=>'Search Console Average Position','description'=>'Average position reported by Google Search Console.'],'search_type'=>['label'=>'نوع جستجو','term'=>'Search Type'],'sync'=>['label'=>'همگام‌سازی','term'=>'Sync'],'manual_sync'=>['label'=>'همگام‌سازی دستی','term'=>'Manual Sync'],'last_sync'=>['label'=>'آخرین همگام‌سازی','term'=>'Last Sync'],'sync_status'=>['label'=>'وضعیت همگام‌سازی','term'=>'Sync Status'],
 'oauth'=>['label'=>'OAuth','term'=>'OAuth 2.0'],'callback'=>['label'=>'نشانی بازگشت','term'=>'OAuth Callback / Redirect URI'],'module'=>['label'=>'ماژول','term'=>'Module'],'modules'=>['label'=>'ماژول‌ها','term'=>'Modules'],'feature_flag'=>['label'=>'پرچم قابلیت','term'=>'Feature Flag'],'settings'=>['label'=>'تنظیمات سامانه','term'=>'System Settings'],'user'=>['label'=>'کاربر','term'=>'User'],'users'=>['label'=>'کاربران','term'=>'Users'],'role'=>['label'=>'نقش','term'=>'Role'],'roles'=>['label'=>'نقش‌ها','term'=>'Roles'],'permission'=>['label'=>'مجوز دسترسی','term'=>'Permission'],'permissions'=>['label'=>'مجوزهای دسترسی','term'=>'Permissions'],'rbac'=>['label'=>'کنترل دسترسی مبتنی بر نقش','term'=>'RBAC — Role-Based Access Control'],
 'migration'=>['label'=>'مهاجرت پایگاه داده','term'=>'Database Migration'],'schema'=>['label'=>'نسخه ساختار پایگاه داده','term'=>'Schema Version'],'app_version'=>['label'=>'نسخه برنامه','term'=>'Application Version'],'queue'=>['label'=>'صف','term'=>'Queue'],'job'=>['label'=>'کار صف','term'=>'Job'],'job_status'=>['label'=>'وضعیت کار صف','term'=>'Job Status'],'retry'=>['label'=>'تلاش دوباره','term'=>'Retry'],'pending'=>['label'=>'در انتظار','term'=>'Pending'],'running'=>['label'=>'در حال اجرا','term'=>'Running'],'completed'=>['label'=>'تکمیل‌شده','term'=>'Completed'],'failed'=>['label'=>'ناموفق','term'=>'Failed'],'api'=>['label'=>'API','term'=>'API — Application Programming Interface'],'endpoint'=>['label'=>'نقطه پایانی','term'=>'Endpoint'],'rate_limit'=>['label'=>'محدودسازی نرخ درخواست','term'=>'Rate Limiting'],
];
