<?php
return [
 'validation.action'=>'عملیات انجام نشد. ورودی‌ها و سطح دسترسی را بررسی کنید.','validation.unauthorized'=>'مجوز انجام این عملیات را ندارید.','validation.email'=>'یک ایمیل معتبر وارد کنید.','validation.admin_email'=>'ایمیل معتبر مدیر را وارد کنید.','validation.name'=>'نام الزامی و حداکثر ۱۰۰ نویسه است.','validation.admin_name'=>'نام مدیر الزامی و حداکثر ۱۰۰ نویسه است.','validation.password'=>'گذرواژه باید بین ۱۲ تا ۱۰۲۴ نویسه باشد.','validation.admin_password'=>'گذرواژه مدیر باید بین ۱۲ تا ۱۰۲۴ نویسه باشد.','validation.app_name'=>'نام برنامه الزامی و حداکثر ۱۲۰ نویسه است.',
 'validation.website_missing'=>'وب‌سایت یافت نشد.','validation.keyword_missing'=>'کلیدواژه یافت نشد.','validation.user_missing'=>'کاربر یافت نشد.','validation.role_missing'=>'نقش یافت نشد.','validation.rank_missing'=>'بررسی رتبه یافت نشد.','validation.connection_missing'=>'اتصال سرچ کنسول یافت نشد.','validation.property_missing'=>'ویژگی سرچ کنسول یافت نشد.','validation.sync_missing'=>'همگام‌سازی سرچ کنسول یافت نشد.','validation.comparison_missing'=>'مقایسه یافت نشد.',
 'validation.website_input'=>'نشانی معتبر وب‌سایت و توضیحی حداکثر ۵۰۰۰ نویسه‌ای وارد کنید.','validation.website_name'=>'نام وب‌سایت الزامی و حداکثر ۱۵۰ نویسه است.','validation.website_url'=>'نشانی وب‌سایت باید فقط مبدأ باشد و مسیر نداشته باشد.','validation.website_origin'=>'نشانی باید مبدأ HTTP یا HTTPS و بدون اطلاعات ورود، درگاه، Query یا Fragment باشد.','validation.domain'=>'یک دامنه ASCII معتبر وارد کنید؛ دامنه بین‌المللی را ابتدا به Punycode تبدیل کنید.','validation.website_duplicate'=>'این دامنه پیش‌تر در حساب شما ثبت شده است.','validation.website_archived'=>'وب‌سایت از قبل بایگانی شده است.','validation.website_archived_edit'=>'وب‌سایت بایگانی‌شده قابل ویرایش نیست.','validation.website_archived_settings'=>'تنظیمات وب‌سایت بایگانی‌شده قابل تغییر نیست.',
 'validation.keyword'=>'کلیدواژه الزامی، حداکثر ۲۵۵ نویسه و بدون نویسه کنترلی است.','validation.keyword_duplicate'=>'این پیکربندی ردیابی کلیدواژه برای وب‌سایت تکراری است.','validation.keyword_archived'=>'کلیدواژه‌های وب‌سایت بایگانی‌شده قابل تغییر نیستند.','validation.keyword_active'=>'فقط کلیدواژه فعال قابل بررسی است.','validation.target_url'=>'نشانی هدف باید URL معتبر HTTP یا HTTPS باشد.','validation.target_url_safe'=>'نشانی هدف باید HTTP یا HTTPS و بدون اطلاعات ورود یا Fragment باشد.','validation.engine'=>'یک موتور جستجوی پشتیبانی‌شده انتخاب کنید.','validation.country'=>'کد کشور پشتیبانی‌شده ISO 3166-1 alpha-2 را انتخاب کنید.','validation.language'=>'زبان باید برچسب معتبر BCP 47 باشد.','validation.device'=>'یک دستگاه پشتیبانی‌شده انتخاب کنید.','validation.timezone_status'=>'منطقه زمانی و وضعیت معتبر انتخاب کنید.',
 'validation.rate_rank'=>'سقف درخواست بررسی رتبه رسیده است؛ کمی بعد دوباره تلاش کنید.','validation.rank_disabled'=>'بررسی دستی رتبه موقتاً غیرفعال است.','validation.rank_archived'=>'برای وب‌سایت بایگانی‌شده نمی‌توان بررسی رتبه اجرا کرد.','validation.rank_adapter'=>'هیچ رابط تأییدشده‌ای برای اجرای زنده ردیابی رتبه پیکربندی نشده است.','validation.rank_url'=>'نشانی رتبه‌گرفته معتبر نیست.','validation.rank_result'=>'دسته‌بندی نتیجه رتبه معتبر نیست.',
 'validation.sc_disabled'=>'سرچ کنسول غیرفعال است.','validation.sc_not_connected'=>'سرچ کنسول متصل نیست.','validation.sc_dates'=>'تاریخ‌های سرچ کنسول باید در محدوده تاریخچه و سقف پیکربندی‌شده باشند.','validation.sc_range'=>'بازه تاریخ معتبر سرچ کنسول انتخاب کنید.','validation.sc_dashboard_range'=>'بازه تاریخ معتبر برای داشبورد سرچ کنسول انتخاب کنید.','validation.sc_filters'=>'فیلترهای معتبر داشبورد سرچ کنسول را انتخاب کنید.','validation.sc_type'=>'نوع جستجوی پشتیبانی‌شده سرچ کنسول را انتخاب کنید.','validation.sc_rate'=>'سقف همگام‌سازی سرچ کنسول رسیده است؛ بعداً دوباره تلاش کنید.','validation.sc_sync_disabled'=>'همگام‌سازی سرچ کنسول موقتاً غیرفعال است.','validation.query'=>'فیلتر عبارت جستجو معتبر نیست.','validation.page'=>'فیلتر صفحه معتبر نیست.',
 'validation.identifier'=>'شناسه معتبر نیست.','validation.pagination'=>'شماره یا اندازه صفحه معتبر نیست.','validation.date_range'=>'بازه تاریخ معتبر نیست.','validation.report_range'=>'بازه تاریخ گزارش معتبر نیست.','validation.report_filters'=>'فیلترهای گزارش معتبر نیستند.','validation.report_type'=>'نوع گزارش شناخته نشد.','validation.report_disabled'=>'ماژول گزارش‌ها غیرفعال است.','validation.csv'=>'خروجی CSV در دسترس نیست.',
 'validation.module_state'=>'وضعیت ماژول معتبر نیست.','validation.module_missing'=>'ماژول نصب نشده است.','validation.module_locked'=>'ماژول بنیادی قابل غیرفعال‌سازی نیست.','validation.setting_scope'=>'دامنه تنظیم معتبر نیست.','validation.setting_text'=>'متن تنظیم معتبر نیست.','validation.setting_timezone'=>'منطقه زمانی معتبر نیست.','validation.setting_secure'=>'تنظیم حساس باید از طریق رازهای محیط استقرار انجام شود.','validation.setting_unknown'=>'تنظیم شناخته نشد.','validation.setting_boolean'=>'مقدار تنظیم باید بله یا خیر باشد.','validation.setting_allowed'=>'مقدار انتخاب‌شده برای تنظیم مجاز نیست.','validation.feature_flag'=>'این تنظیم پرچم قابلیت نیست.',
 'validation.self_disable'=>'نمی‌توانید حساب خود را غیرفعال کنید.','validation.self_delete'=>'نمی‌توانید حساب خود را حذف کنید.','validation.last_admin_disable'=>'آخرین مدیر فعال قابل غیرفعال‌سازی نیست.','validation.last_admin_delete'=>'آخرین مدیر فعال قابل حذف نیست.','validation.admin_role'=>'نقش مدیر باید مجوز داخلی roles.manage را حفظ کند.','validation.roles_missing'=>'یک یا چند نقش وجود ندارند.','validation.permissions_missing'=>'یک یا چند مجوز دسترسی وجود ندارند.','validation.assignment'=>'انتخاب تخصیص معتبر نیست.',
];
